spring.application.name=spring-ai-test-profile

# ollama models (for different tasks) and the provider of the models
app.ai.conversation.model=gpt-4o-mini
app.ai.conversation.provider=openai
app.ai.general.model=gpt-4o-mini
app.ai.general.provider=openai
app.ai.vision.model=gpt-4o-mini
app.ai.vision.provider=openai
app.ai.embedding.provider=ollama
app.ai.embedding.model=nomic-embed-text
app.ai.search.similarity-threshold=0.35
spring.ai.model.embedding=none
# db
spring.datasource.url=jdbc:postgresql://localhost:5432/ai-invoice
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768

