CREATE TABLE invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier VARCHAR(255),
    invoice_number VARCHAR(255),
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(255)
);